### PR TITLE
Update Go dependencies

### PR DESCRIPTION
**Pull request by SuperQ**
* Update all Go modules to the latest versions.
* Update Go minimum version to 1.17.
* Update Go modules file format to 1.17.
* Fixup `go fmt ./...`.
* Enable dependabot.

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
Looks like PRs aren't triggering GitHub actions.

**Comment by shawnps** [comment]
@SuperQ Thanks -- I've reached out to the repo admins to see if we can enable CI actions for PRs. Will comment  when I hear back.

**Comment by shawnps** [comment]
@SuperQ any chance you could push this branch again so we can see if [this change to the GitHub Actions](https://github.com/fastly/fastly-exporter/commit/c07310f8ddcbc8bc49c10cda0de57140001570d8) worked? 

Although I'm not sure if pushing the branch will trigger it, or if it only affects newly-created PRs going forward.

**Comment by SuperQ** [comment]
Done, looks like it's waiting for approval to run. I also added a dependabot config so modules will get automatic update PRs.

**Review by shawnps — APPROVED** [review]

**Review by hermanschaaf — APPROVED** [review]

**Pull request merged**
