### PR TITLE
Use package ff, enabling env vars and config files

### PR DESCRIPTION
**Pull request by peterbourgon**
Alternative to #45. @dgarlitt, does this serve the purpose?

### CODE REVIEW

**Comment by peterbourgon** [comment]
Oops, you also want FASTLY_EXPORTER_SERVICE_IDS split on commas, eh?

**Comment by mrnetops** [comment]
@peterbourgon we probably want that for all fields that can potentially do multiple values, whitelist, blacklist etc.  

I like that you just tossed in a potential config file too ;)

**Comment by peterbourgon** [comment]
Unfortunately the regexp fields can contain commas. Is it smart to allow those to be provided via env vars if they're not a complete solution?

**Comment by mrnetops** [comment]
Hmmm.  Initial less clean thoughts

0) Is there a reasonable way to support bash arrays in golang?
1) regexp from environment variables only get one value, but being regexps, you can OR them together.  i.e. "this|that" vs "this,that"
2) less clean, given that ',' is likely only going to be used for -service, -service-whitelist and -service-blacklist we could include the addendum that "," is a hard separator and inline commas would need to be replaced by "."

...I did say less clean thoughts ;)

**Comment by peterbourgon** [comment]
@dgarlitt Could you say a bit about why you want more flags controllable by env vars? Is it not possible to pass flags in your runtime environment?

**Pull request merged**
