### PR TITLE
add req_body_bytes_total and bereq_body_bytes_total metrics

### PR DESCRIPTION
**Pull request by gaashh**
Add req_body_bytes_total and bereq_body_bytes_total metrics, the matching pairs of the existing req_header_bytes_total and bereq_header_bytes_total metrics

### CODE REVIEW

**Comment by peterbourgon** [comment]
There are probably several more fields that have become available since I first captured the response structure from rt.fastly.com, let me do a bit more research...

**Comment by gaashh** [comment]
Sure, the more the merrier :-)
Thanks,
Gaash

**Comment by gaashh** [comment]
Can you please update with your additional metrics research status?

**Comment by peterbourgon** [comment]
Solved in #51, sorry it took so incredibly long, it was a real Pandora's box.

**Comment by peterbourgon** [comment]
Alpha release of the new fields here: https://github.com/peterbourgon/fastly-exporter/releases/tag/v6.0.0-alpha.1

If you can give it a try and report any issues I'd appreciate it :)

**Pull request closed without merging**
