### PR TITLE
enable exclusion of measurements as cli arg

### PR DESCRIPTION
**Pull request by j18e**
this feature will allow for the explicit exclusion of measurements using command line args. Have tested thoroughly.

### CODE REVIEW

**Comment by peterbourgon** [comment]
Can you give a brief description of your use case?

I'm OK with this feature, but I would implement it differently :) I'll happily do that work once I understand what you're aiming for.

**Comment by j18e** [comment]
we're using this at finn.no (in Norway) and it's returning over 60,000 time series. We're trying to cut down on this and the main way we wish to do this is excluding metrics we don't actually use from scrapes.

I know this is achievable through the scrape configs in prometheus itself, but this results in somewhat of a scattered configuration, which we're trying to avoid.

Would love to hear how you'd implement it. I tried to do it with minimal code changes but I'm sure it could have been done better :)

Thanks for the quick response!

**Comment by peterbourgon** [comment]
Would it make sense to have this work like the whitelist and blacklist flags for service names, except applied to metric names?

**Comment by j18e** [comment]
Absolutely! I'll work on it and get back to you

**Comment by peterbourgon** [comment]
Oh, I'm happy to do it — it will trigger some other refactors. Are you OK with using a single regex string to {whitelist, blacklist} the metrics you {want, don't want} — or would you strongly prefer to repeat flags?

**Comment by peterbourgon** [comment]
After a bit of thought, I think I can make the -include-regex and -exclude-regex flags repeatable in all cases.

**Comment by j18e** [comment]
Okay that sounds good. Thanks a bunch!

Jamie Wiebe

**Comment by peterbourgon** [comment]
Solved with #40, thanks for the use case.

**Pull request closed without merging**
