### PR TITLE
Refactor labels used in realtime package

### PR DESCRIPTION
**Pull request by mikelorant**
Previously, each metric had a static list of labels to be applied. By changing this to a variable, we can now define a default set of labels plus any extra labels.

These changes are preparation work for introducing a feature allowing for the removal of the `datacenter` label.

### CODE REVIEW

**Comment by mikelorant** [comment]
@leklund Taking a different approach of smaller pull requests working towards the feature of being able to remove the `datacenter` label. This should significantly help with reducing the size of the next pull request and hopefully speed up the approval process.

**Comment by mikelorant** [comment]
If you are happy with these results, I will put up 2 more pull requests to refactor the `domain` and `origin` packages to use the same approach.

**Comment by mikelorant** [comment]
Branches for:

- [Domain][1]
- [Origin][2]

[1]: https://github.com/fastly/fastly-exporter/compare/main...mikelorant:fastly-exporter:refactor/labels-domain
[2]: https://github.com/fastly/fastly-exporter/compare/main...mikelorant:fastly-exporter:refactor/labels-origin

**Comment by leklund** [comment]
@mikelorant This can be closed, correct?

**Comment by mikelorant** [comment]
Closing this one as an alternative approach was taken in #169.

**Pull request closed without merging**
